<?php

/**
 * @file
 * Default content UI module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\default_content_ui\Form\ImportDefaultContentForm;

/**
 * Implements hook_entity_presave().
 */
function default_content_ui_entity_presave(EntityInterface $entity) {
  if (Drupal::state()->get(ImportDefaultContentForm::LOCK_ID, FALSE) && $entity->isNew()) {
    $storage = Drupal::entityTypeManager()->getStorage($entity->getEntityTypeId());
    $exist_entities = $storage->loadByProperties([
      'uuid' => $entity->uuid(),
    ]);
    $exist_entity = reset($exist_entities);
    if ($exist_entity instanceof EntityInterface) {
      // Delete previous entity.
      $exist_entity->delete();
    }
  }
}

/**
 * Implements hook_file_download().
 */
function default_content_ui_file_download($uri): array {
  if (Drupal::currentUser()->hasPermission('access to default content form')) {
    return [
      'Content-Type' => \Drupal::service('file.mime_type.guesser')->guessMimeType($uri),
      'Content-Length' => filesize($uri),
      'Cache-Control' => 'no-cache, must-revalidate',
    ];
  }

  return [];
}
